
name: CI
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name : Checkout source code
      uses: actions/checkout@v2
    
    - name : Setup Elm environment
      uses: jorelali/setup-elm@v2
      with:
        elm-version: 0.19.1
    - run: cd app && elm make src/Main.elm
